name: Benchmark
on:
  push:
    branches:
      - main

permissions:
  contents: write
  deployments: write

env:
  CARGO_TERM_COLOR: always
  AOC_SESSION: ${{ secrets.AOC_SESSION }}

jobs:
  benchmark:
    name: Run Rust benchmark example
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Update local toolchain
        run: rustup update

      - name: Run benchmark
        run: cargo bench | tee output.txt
        working-directory: rs

      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        working-directory: rs
        with:
          name: Rust Benchmark
          tool: 'cargo'
          output-file-path: output.txt
          benchmark-data-dir-path: "/docs/bench"
          auto-push: false

      - name: Push benchmark result
        run: git push gh-pages:gh-pages
