name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  AOC_SESSION: ${{ secrets.AOC_SESSION }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Update local toolchain
        run: |
          rustup update
          rustup component add clippy

      - name: Toolchain info
        run: |
          cargo --version --verbose
          rustc --version
          cargo clippy --version

#      - name: Lint
#        run: |
#          cargo fmt -- --check
#          cargo clippy -- -D warnings
#        working-directory: rs

      - name: Build
        run: cargo build --verbose --release
        working-directory: rs

      - name: Run tests
        run: cargo test --verbose
        working-directory: rs
